# Generated by Django 4.1.2 on 2022-11-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaussure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chaussure', models.CharField(max_length=1000000)),
                ('description', models.CharField(max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('photos', models.ImageField(upload_to='')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enfant', models.CharField(max_length=1000000)),
                ('description', models.CharField(max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('photos', models.ImageField(upload_to='')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Femme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_femme', models.CharField(max_length=1000000)),
                ('description', models.CharField(max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('photos', models.ImageField(upload_to='')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Homme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_homme', models.CharField(max_length=1000000)),
                ('description', models.CharField(max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('photos', models.ImageField(upload_to='')),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000000)),
                ('prenom', models.CharField(default=None, max_length=1000000)),
                ('numeros', models.IntegerField()),
                ('email', models.EmailField(max_length=1000000)),
                ('password', models.CharField(max_length=1000000)),
                ('genre', models.CharField(max_length=1000000)),
            ],
        ),
    ]
