# Generated by Django 4.1.2 on 2022-11-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaussure',
            old_name='nombre',
            new_name='nombre_article',
        ),
        migrations.RenameField(
            model_name='enfant',
            old_name='nombre',
            new_name='nombre_article',
        ),
        migrations.RenameField(
            model_name='femme',
            old_name='nombre',
            new_name='nombre_article',
        ),
        migrations.RenameField(
            model_name='homme',
            old_name='nombre',
            new_name='nombre_article',
        ),
        migrations.RemoveField(
            model_name='chaussure',
            name='numeros',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='numeros',
        ),
        migrations.RemoveField(
            model_name='femme',
            name='numeros',
        ),
        migrations.RemoveField(
            model_name='homme',
            name='numeros',
        ),
    ]
