# Generated by Django 4.1.2 on 2022-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_nombre_chaussure_nombre_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaussure',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='femme',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homme',
            name='prix',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
